<?php

use App\Http\Controllers\Api\Admin\IncidentCategoryController;
use App\Http\Controllers\Api\Admin\IncidentTypeDefaultResourceController;
use App\Http\Controllers\Api\Admin\IncidentTypeFieldController;
use App\Http\Controllers\Api\Admin\IncidentTypeController;
use App\Http\Controllers\Api\Admin\ResourceTypeController;
use App\Http\Controllers\Api\Admin\ResourceTypeCategoryController;
use App\Http\Controllers\Api\Admin\SettingsController;
use App\Http\Controllers\Api\Admin\SitrepRelayDeliveryController;
use App\Http\Controllers\Api\Admin\SummaryController;
use App\Http\Controllers\Api\Admin\TeamCategoryController;
use App\Http\Controllers\Api\Admin\TeamController;
use App\Http\Controllers\Api\Admin\TeamInventoryController;
use App\Http\Controllers\Api\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'role:admin'])->prefix('/admin')->group(function (): void {
    Route::get('/summary', [SummaryController::class, 'show']);
    Route::get('/users', [UserController::class, 'index']);
    Route::post('/users', [UserController::class, 'store']);
    Route::get('/users/{user}', [UserController::class, 'show']);
    Route::post('/users/{user}', [UserController::class, 'update']);
    Route::delete('/users/{user}', [UserController::class, 'destroy']);
    Route::get('/incident-categories', [IncidentCategoryController::class, 'index']);
    Route::post('/incident-categories', [IncidentCategoryController::class, 'store']);
    Route::post('/incident-categories/{category}', [IncidentCategoryController::class, 'update']);
    Route::delete('/incident-categories/{category}', [IncidentCategoryController::class, 'destroy']);
    Route::get('/incident-types', [IncidentTypeController::class, 'index']);
    Route::post('/incident-types', [IncidentTypeController::class, 'store']);
    Route::get('/incident-types/{type}', [IncidentTypeController::class, 'show']);
    Route::post('/incident-types/{type}', [IncidentTypeController::class, 'update']);
    Route::delete('/incident-types/{type}', [IncidentTypeController::class, 'destroy']);
    Route::get('/incident-type-fields', [IncidentTypeFieldController::class, 'index']);
    Route::post('/incident-type-fields', [IncidentTypeFieldController::class, 'store']);
    Route::post('/incident-type-fields/{field}', [IncidentTypeFieldController::class, 'update']);
    Route::delete('/incident-type-fields/{field}', [IncidentTypeFieldController::class, 'destroy']);
    Route::post('/incident-types/{type}/default-resources', [IncidentTypeDefaultResourceController::class, 'store']);
    Route::post('/incident-types/{type}/default-resources/{default}', [IncidentTypeDefaultResourceController::class, 'update']);
    Route::delete('/incident-types/{type}/default-resources/{default}', [IncidentTypeDefaultResourceController::class, 'destroy']);
    Route::get('/resource-types', [ResourceTypeController::class, 'index']);
    Route::post('/resource-types', [ResourceTypeController::class, 'store']);
    Route::post('/resource-types/{resourceType}', [ResourceTypeController::class, 'update']);
    Route::delete('/resource-types/{resourceType}', [ResourceTypeController::class, 'destroy']);
    Route::get('/resource-type-categories', [ResourceTypeCategoryController::class, 'index']);
    Route::post('/resource-type-categories', [ResourceTypeCategoryController::class, 'store']);
    Route::post('/resource-type-categories/{resourceTypeCategory}', [ResourceTypeCategoryController::class, 'update']);
    Route::delete('/resource-type-categories/{resourceTypeCategory}', [ResourceTypeCategoryController::class, 'destroy']);
    Route::get('/team-categories', [TeamCategoryController::class, 'index']);
    Route::post('/team-categories', [TeamCategoryController::class, 'store']);
    Route::post('/team-categories/{teamCategory}', [TeamCategoryController::class, 'update']);
    Route::delete('/team-categories/{teamCategory}', [TeamCategoryController::class, 'destroy']);
    Route::get('/teams', [TeamController::class, 'index']);
    Route::post('/teams', [TeamController::class, 'store']);
    Route::get('/teams/{team}', [TeamController::class, 'show']);
    Route::post('/teams/{team}', [TeamController::class, 'update']);
    Route::delete('/teams/{team}', [TeamController::class, 'destroy']);
    Route::post('/teams/{team}/inventories', [TeamInventoryController::class, 'store']);
    Route::post('/teams/{team}/inventories/{inventory}', [TeamInventoryController::class, 'update']);
    Route::delete('/teams/{team}/inventories/{inventory}', [TeamInventoryController::class, 'destroy']);
    Route::get('/settings', [SettingsController::class, 'show']);
    Route::post('/settings', [SettingsController::class, 'update']);
    Route::get('/sitrep-relay-deliveries', [SitrepRelayDeliveryController::class, 'index']);
    Route::post('/sitrep-relay-deliveries/{delivery}/retry', [SitrepRelayDeliveryController::class, 'retry']);
});
