import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync('resources/js/surfaces/citizenSurface.js', 'utf8');
const snippet = source.slice(source.indexOf("    let callerPeerState = '';"), source.indexOf('    if (overlay) {', source.indexOf("    let callerPeerState = '';")));
let connected = true;
let requests = 0;
let timerId = 0;
const timers = new Map();
const runtime = {latestSessionId: 45, callRuntime: {getState: () => ({peerConnected: connected})}};
const context = vm.createContext({appState: {runtime: {callerLiveModal: runtime}}, callSessionId:45, payload:{id:34}, CALLER_REMOTE_DISCONNECT_GRACE_MS:10000, CALLER_REMOTE_HEARTBEAT_TIMEOUT_MS:12000, window:{setTimeout(fn){timers.set(++timerId, fn); return timerId;}}, clearCallerLiveRemoteDisconnectTimer(){timers.delete(context.appState.runtime.callerLiveRemoteDisconnectTimerId); context.appState.runtime.callerLiveRemoteDisconnectTimerId = null;}, clearCallerLiveRemoteHeartbeatTimer(){timers.delete(context.appState.runtime.callerLiveRemoteHeartbeatTimerId);}, syncOperatorDisconnectNotice(){}, logCallFlow(){}, Date, console, fetchJson(){requests++; return Promise.resolve({call_session:{status:'ended'}});}, withCallerRemoteDisconnectCleanupTimeout:p=>p, patchIncidentCallSession:p=>p, syncCallerCurrentIncident(){}, showToast(){}, close:async()=>{}, renderSurface:async()=>{}});
vm.runInContext(snippet + '\nglobalThis.api = {scheduleCallerOperatorDisconnectCleanup, completeCallerOperatorDisconnect, cancelCallerOperatorDisconnectCleanup, resetCallerOperatorHeartbeatWatch, setPeerState(s){callerPeerState=s;}};', context);
context.api.scheduleCallerOperatorDisconnectCleanup('heartbeat-timeout');
assert.equal(timers.size,0, 'Healthy media must not start cleanup');
connected=false;
context.api.setPeerState('disconnected');
context.api.scheduleCallerOperatorDisconnectCleanup('disconnected');
context.api.cancelCallerOperatorDisconnectCleanup('heartbeat');
assert.equal(timers.size,1, 'Heartbeat must not cancel failed media cleanup');
connected=true;
await context.api.completeCallerOperatorDisconnect('disconnected');
assert.equal(requests,0, 'Recovery before expiry must prevent cleanup request');
connected=false;
context.api.setPeerState('failed');
await context.api.completeCallerOperatorDisconnect('failed');
assert.equal(requests,1, 'Persistent media failure must end session');
console.log('Disconnect watchdog regressions passed.');
