import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync('resources/js/surfaces/surfaceShared.js','utf8');
let applied=0;
const peer={signalingState:'have-local-offer',async setRemoteDescription(){applied++;this.signalingState='stable';}};
const answer=source.slice(source.indexOf("        if (signalType === 'answer') {"),source.indexOf("        if (signalType === 'ice-candidate') {",source.indexOf("        if (signalType === 'answer') {")));
const context=vm.createContext({signalType:'answer',peerConnection:peer,payload:{sdp:'answer'},senderUserId:'3',callSessionId:48,viewerRole:'citizen',logCallFlow(){},normalizeRealtimeSdp:s=>s,attachPendingIceCandidates:async()=>{},state:{startedOffer:true},console});
vm.runInContext('globalThis.answer=async()=>{'+answer+'};',context);
await context.answer();await context.answer();
assert.equal(applied,1,'Duplicate answer must be ignored');
peer.signalingState='closed';await context.answer();assert.equal(applied,1);
let offers=0;
peer.remoteDescription={type:'answer'};peer.createOffer=async()=>{offers++;return{type:'offer',sdp:'offer'};};peer.setLocalDescription=async d=>{peer.localDescription=d;};peer.getSenders=()=>[];
Object.assign(context,{MediaStream:class{},isPublicViewerRole:()=>true,debugMedia(){},remoteUserId:'3',ensurePeerConnectionWithLocalAudio:async()=>peer,applyLocalVideoTrack:async()=>{},resetRemotePeerConnection(){},buildCallSignalPayload:()=>({}),showToast(){}});
context.state={startedOffer:false,client:{isOpen:()=>true,sendRequest(){}},callRoom:'call.session.48'};
const offer=source.slice(source.indexOf('    const createAndSendOffer ='),source.indexOf('    const updateLocalVideoStream ='));
vm.runInContext(offer+'globalThis.offer=createAndSendOffer;',context);
await context.offer({force:false,resetPeer:false});assert.equal(offers,0,'Late ready must not renegotiate');
await context.offer({force:true,resetPeer:false});assert.equal(offers,1,'Explicit media change must renegotiate');
console.log('PASS duplicate answer and late ready handling');