import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {startStaticServer} from '../../public/vendor/helpers.pbb.ph/tests/_support/static-server.mjs';
const server=await startStaticServer({rootDir:process.cwd(),port:0});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
try {for(const bundle of [false,true]) {
 const page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 const load=async()=>{await page.goto(server.origin+'/tests/browser/chat-composer-integration.html'+(bundle?'?bundle':''));await page.waitForFunction(()=>window.ready);};
 await load();
 for(const name of ['Attach file','Attach Video','Attach Audio'])assert.equal(await page.getByRole('button',{name,exact:true}).count(),1);
 await page.getByRole('button',{name:'Attach Audio',exact:true}).click();
 await page.getByRole('button',{name:'Start recording',exact:true}).click();
 await page.waitForTimeout(600);
 await page.getByRole('button',{name:'Stop recording',exact:true}).click();
 await page.getByRole('button',{name:'Attach recording',exact:true}).click();
 await page.waitForFunction(()=>chat.uploadQueueApi.getItems().length===1);
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems()[0].kind),'audio');
 assert.equal(await page.evaluate(()=>mediaTracks.every(track=>track.readyState==='ended')),true);
 assert.equal(await page.evaluate(()=>chat.composerApi.getValue()),'Preserved draft');
 assert.equal(await page.evaluate(()=>chatClient.requests.some(item=>item.type==='chat.message.publish')),false,'Capture cannot auto-send');
 assert.equal(await page.evaluate(()=>chat.composerApi.getState().attachmentCount),1);
 await page.evaluate(()=>{chat.composerApi.setValue('');});
 assert.equal(await page.getByRole('button',{name:'Send',exact:true}).isDisabled(),false,'Validated attachment-only messages can be sent');
 await page.evaluate(()=>{chat.composerApi.setValue('Preserved draft');window.failChunk=true;});
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await page.waitForFunction(()=>toasts.some(value=>value.includes('draft has been kept')));
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems().length),1);
 assert.equal(await page.evaluate(()=>chat.composerApi.getValue()),'Preserved draft');
 await page.evaluate(()=>{window.failChunk=false;chat.composerApi.setValue('');});
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await page.waitForFunction(()=>chatClient.requests.some(item=>item.type==='chat.message.publish'));
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems().length),1,'Draft retained before acknowledgement');
 assert.equal(await page.evaluate(()=>chatClient.requests.find(item=>item.type==='chat.message.publish').payload.text),'Audio attachment');
 assert.equal(await page.evaluate(()=>chatClient.requests.some(item=>item.type==='sandbox.attachment.chunk.publish'&&item.payload.chunk_data.length>0)),true,'Codec-qualified recording sends actual chunks');
 await page.evaluate(()=>{const item=chatClient.requests.find(item=>item.type==='chat.message.publish');chatClient.options.onMessage({phase:'ack',type:item.type,id:item.id});});
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems().length),0);
 assert.equal(await page.evaluate(()=>chat.composerApi.getState().attachmentCount),0);
 assert.equal(await page.evaluate(()=>createdUrls.filter(url=>url.startsWith('blob:')).every(url=>revokedUrls.includes(url))),true);
 await load();
 await page.getByRole('button',{name:'Attach Video',exact:true}).click();
 await page.getByRole('button',{name:'Start recording',exact:true}).click();
 await page.waitForTimeout(600);
 await page.getByRole('button',{name:'Stop recording',exact:true}).click();
 await page.getByRole('button',{name:'Attach recording',exact:true}).click();
 await page.waitForFunction(()=>chat.uploadQueueApi.getItems().length===1);
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems()[0].kind),'video');
 assert.equal(await page.evaluate(()=>mediaTracks.every(track=>track.readyState==='ended')),true);
 assert.equal(await page.evaluate(()=>chatClient.requests.some(item=>item.type==='chat.message.publish')),false);
 await load();
 await page.locator('input[type=file]').setInputFiles({name:'too-large.png',mimeType:'image/png',buffer:Buffer.alloc(1048577)});
 await page.waitForFunction(()=>toasts.some(value=>value.includes('per-file limit')));
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems().length),0);
 // Two picker batches arriving while the first file is being read share one policy budget.
 await page.evaluate(()=>{delayRead=true;const input=document.querySelector('input[type=file]');const select=name=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(600000)],name,{type:'image/png'}));input.files=transfer.files;input.dispatchEvent(new Event('change'));};select('one.png');select('two.png');});
 await page.waitForFunction(()=>typeof completeRead==='function');
 await page.evaluate(()=>{delayRead=false;completeRead();});
 await page.waitForFunction(()=>toasts.some(value=>value.includes('total attachment limit')));
 assert.equal(await page.evaluate(()=>chat.uploadQueueApi.getItems().length),1);
 await page.evaluate(()=>chat.destroy());
 assert.equal(await page.evaluate(()=>createdUrls.every(url=>revokedUrls.includes(url))),true);
 await load();
 await page.evaluate(()=>delayRead=true);
 await page.locator('input[type=file]').setInputFiles({name:'late.png',mimeType:'image/png',buffer:Buffer.from([1,2,3])});
 await page.waitForFunction(()=>typeof completeRead==='function');
 await page.evaluate(()=>{chat.destroy();delayRead=false;completeRead();});
 await page.waitForFunction(()=>createdUrls.every(url=>revokedUrls.includes(url)));
 assert.equal(await page.evaluate(()=>chat.composerApi.getState().attachmentCount),0,'Late preparation cannot repopulate a disposed queue');
 assert.deepEqual(errors,[]);await page.close();console.log('PASS actual Hotline composer integration '+(bundle?'bundle':'source'));
}}finally{await browser.close();await server.close();}
