import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const operatorSurface = await readFile(new URL('../../resources/js/surfaces/operatorSurface.js', import.meta.url), 'utf8');
const surfaceShared = await readFile(new URL('../../resources/js/surfaces/surfaceShared.js', import.meta.url), 'utf8');
const citizenSurface = await readFile(new URL('../../resources/js/surfaces/citizenSurface.js', import.meta.url), 'utf8');

assert.match(operatorSurface, /const liveMessages = appState\.runtime\.operatorWorkbenchChat\?\.getMessages\?\.\(\)/);
assert.match(operatorSurface, /payload\.messages = liveMessages/);

assert.match(surfaceShared, /function normalizeChatMessageAttachments\(attachments\)/);
assert.match(surfaceShared, /const alreadyNormalized = Object\.prototype\.hasOwnProperty\.call\(message \?\? \{\}, 'direction'\)/);
assert.match(surfaceShared, /senderName: message\.senderName \?\? formatStatusLabel/);
assert.match(surfaceShared, /senderAvatar: message\.senderAvatar \?\? message\.sender_avatar \?\? message\.sender\?\.avatar \?\? ''/);
assert.match(surfaceShared, /senderAvatar: message\.sender_avatar \?\? message\.sender\?\.avatar \?\? ''/);
assert.match(surfaceShared, /timestamp: message\.timestamp \?\? formatDateTime\(message\.created_at\)/);
assert.match(surfaceShared, /name: attachment\.name \?\? attachment\.original_filename/);
assert.match(surfaceShared, /const mediaRoomName = incidentId > 0\s+\? `hotline\.media\.incident\.\$\{incidentId\}`/);
assert.match(surfaceShared, /const requestRoomJoin = \(targetRoom\) => \{/);
assert.match(surfaceShared, /requestRoomJoin\(admissionRoom\);\s+requestRoomJoin\(mediaRoomName\);/);
assert.match(surfaceShared, /\[admissionRoom, mediaRoomName\]\.includes\(String\(envelope\?\.room \?\? ''\)\)/);
assert.match(operatorSurface, /function rememberOperatorPendingMediaEvent\(incidentId, media\)/);
assert.match(operatorSurface, /function consumeOperatorPendingMediaEvents\(incidentId\)/);
assert.match(operatorSurface, /rememberOperatorPendingMediaEvent\(nextIncidentId, nextMedia\)/);
assert.match(operatorSurface, /const pendingMedia = consumeOperatorPendingMediaEvents\(payload\?\.id\)/);
assert.match(operatorSurface, /pendingMedia\.forEach\(\(media\) => \{\s+payload\.media = mergeIncidentMediaItems\(payload\.media, media\);/);
assert.match(operatorSurface, /async function refreshWorkbenchOverlay\(payload, stateOverride = null, options = \{\}\) \{\s+prepareOperatorWorkbenchPayload\(payload\);\s+const pendingMedia = consumeOperatorPendingMediaEvents\(payload\?\.id\)/);
assert.match(operatorSurface, /if \(!isActive\) \{\s+if \(changedItems\.length > 0\) \{\s+callSessionTimelineApi\?\.destroy\?\.\(\);\s+callSessionTimelineApi = null;/);
assert.match(operatorSurface, /incident-media-event-received/);
assert.match(operatorSurface, /incident-media-event-applied/);

assert.match(surfaceShared, /const CALL_SESSION_KEEPALIVE_MS = 60 \* 1000/);
assert.match(surfaceShared, /const CALL_SESSION_OPERATOR_READY_RESEND_MS = 1500/);
assert.match(surfaceShared, /const CALL_SESSION_OPERATOR_READY_RESEND_LIMIT = 8/);
assert.match(surfaceShared, /sessionKeepaliveTimerId: null/);
assert.match(surfaceShared, /readyResendTimerId: null/);
assert.match(surfaceShared, /signalQueuesByUser: \{\}/);
assert.match(surfaceShared, /const stopCallSessionKeepalive = \(\) => \{/);
assert.match(surfaceShared, /const startOperatorReadyResend = \(\) => \{/);
assert.match(surfaceShared, /const processSignalEvent = async \(envelope\) => \{/);
assert.match(surfaceShared, /const handleSignalEvent = \(envelope\) => \{/);
assert.match(surfaceShared, /state\.signalQueuesByUser\[senderUserId\]/);
assert.match(surfaceShared, /createAndSendOffer\(\{ force: false, resetPeer: false \}\)/);
assert.match(surfaceShared, /const sendCallSessionKeepalive = \(\) => \{[\s\S]+pingSessionKeepalive\(\)/);
assert.match(surfaceShared, /state\.sessionKeepaliveTimerId = window\.setInterval\(sendCallSessionKeepalive, CALL_SESSION_KEEPALIVE_MS\)/);
assert.match(surfaceShared, /state\.readyResendTimerId = window\.setInterval\(\(\) => \{/);
assert.match(surfaceShared, /startCallHeartbeat\(\);\s+if \(!state\.deferSessionKeepalive\) \{\s+startCallSessionKeepalive\(\);/);
assert.match(surfaceShared, /stopCallHeartbeat\(\);\s+stopCallSessionKeepalive\(\);/);

assert.match(operatorSurface, /incidentPayload\?\.citizen\?\.id/);
assert.match(operatorSurface, /incidentPayload\?\.citizen_id/);
assert.match(operatorSurface, /callSessionPayload\?\.citizen_id/);
assert.doesNotMatch(operatorSurface, /incidentPayload\?\.caller\?\.id[\s\S]*function ensureOperatorCallBridgeAudioHost/);
assert.doesNotMatch(operatorSurface, /incidentPayload\?\.caller_id[\s\S]*function ensureOperatorCallBridgeAudioHost/);
assert.match(operatorSurface, /citizen_id: Number\(response\.incident\?\.citizen_id \?\? 0\)/);
assert.match(operatorSurface, /throw new Error\('Answered call payload is missing incident, session, or citizen identity\.'\)/);
assert.match(operatorSurface, /remoteUserId: String\(citizenId\)/);
assert.match(operatorSurface, /const activeCitizenId = operatorIncidentCitizenId\(payload\)/);
assert.match(operatorSurface, /if \(isActive && payload\?\.id && activeCitizenId\)/);
assert.match(operatorSurface, /remoteUserId: String\(activeCitizenId\)/);
assert.match(operatorSurface, /existingCallStreams: \{\s*localStream: bridgeLocalStream,\s*remoteStream: bridgeRemoteStream,\s*\}/);
assert.match(operatorSurface, /workbench-existing-local-stream-attached/);
assert.match(operatorSurface, /workbench-existing-remote-stream-attached/);
assert.match(surfaceShared, /attachRemoteVideoHost\(nextRemoteVideoHost\)/);
assert.match(operatorSurface, /callRuntime\.attachRemoteVideoHost\?\.\(videoPreviewHost\)/);
assert.match(operatorSurface, /captureManager\?\.syncRemoteVideo\?\.\(hasExistingRemoteVideo,\s*existingStreams\.remoteStream\)/);
assert.match(operatorSurface, /const hasRemoteVideo = stream instanceof MediaStream[\s\S]+captureManager\?\.syncRemoteVideo\?\.\(hasRemoteVideo,\s*stream\)/);
assert.match(operatorSurface, /await state\.remoteVideoSyncPromise\.catch\(\(\) => \{\}\);[\s\S]+await mediaManagers\.producerManager\.close\(\)/);
assert.match(operatorSurface, /void appState\.runtime\.operatorWorkbenchCaptureManager\?\.finalizeAll\?\.\(\);[\s\S]+operator-hangup-ui-refresh-start/);
assert.match(operatorSurface, /void captureManager\?\.finalizeAll\?\.\(\);[\s\S]+remote-disconnect-cleanup-ui-refresh-start/);
assert.match(operatorSurface, /void captureManager\?\.finalizeAll\?\.\(\);[\s\S]+citizen-hangup-ui-refresh-start/);
assert.doesNotMatch(operatorSurface, /await finalizePromise;[\s\S]+operator-hangup-ui-refresh-start/);
assert.match(operatorSurface, /answer-bridge-citizen-hangup-ui-refresh-start/);
assert.match(operatorSurface, /operatorWorkbenchCaptureManager\?\.finalizeAll\?\.\(\)/);
assert.match(operatorSurface, /citizen\.reconnect\.answered[\s\S]+citizen_id: reconnectCitizenId/);
assert.match(operatorSurface, /reconnect-call-modal-connecting[\s\S]+startOperatorAnsweredCallBridge\(root, response\.incident, response\.call_session\)/);
assert.match(citizenSurface, /const payloadCitizenId = String\(payload\?\.citizen_id \?\? ''\)\.trim\(\)/);
assert.match(citizenSurface, /'citizen\.call\.answered'/);
assert.match(citizenSurface, /citizenIdentityRequiredEvents\.has\(eventType\)/);

assert.match(operatorSurface, /function workbenchCallSummaryEndTime\(payload\)/);
assert.match(operatorSurface, /function mountWorkbenchCallSummaryTimer\(overlay, payload\)/);
assert.match(operatorSurface, /isTerminalIncidentStatus\(payload\?\.status\)/);
assert.match(operatorSurface, /data-workbench-call-duration/);
assert.match(operatorSurface, /const endedAtMarkup = isTerminal[\s\S]+Datetime Ended/);
assert.match(operatorSurface, /const callSummaryTimer = mountWorkbenchCallSummaryTimer\(overlay, payload\)/);
