import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const shared=fs.readFileSync('resources/js/surfaces/surfaceShared.js','utf8');
const operator=fs.readFileSync('resources/js/surfaces/operatorSurface.js','utf8');
const track=new EventTarget();Object.assign(track,{id:'citizen-track',kind:'audio',readyState:'live',muted:true,enabled:true});
class Stream {constructor(){this.tracks=[];}getTracks(){return this.tracks;}getAudioTracks(){return this.tracks.filter(t=>t.kind==='audio');}getVideoTracks(){return [];}addTrack(t){this.tracks.push(t);}}
const incoming=new Stream();incoming.addTrack(track);
let bridgeEvents=0,recordings=0;
const recorderState={shuttingDown:false,remoteAudio:null,remoteAudioSyncPromise:Promise.resolve()};
const recordingContext=vm.createContext({state:recorderState,MediaStream:Stream,debugMediaCapture(){},callSessionId:52,caller:{id:5,name:'Citizen'},stopRecorderRuntime:async()=>{},createRecorderRuntime:async()=>{recordings++;return{mediaId:115,sourceTrack:track};}});
const recorder=operator.slice(operator.indexOf('        async ensureRemoteAudio(stream) {'),operator.indexOf('        async syncRemoteVideo(enabled, stream) {'));
vm.runInContext('globalThis.recorder={'+recorder+'};',recordingContext);
const options={onRemoteStream(){bridgeEvents++;}};
const context=vm.createContext({options,peerConnection:{},conferenceState:{remoteStreams:{}},remoteId:'5',state:{mediaMuted:false},MediaStream:Stream,ensureConferenceRemoteStream:(streams,id,create)=>streams[id]??(streams[id]=create()),debugMedia(){},attachHiddenRemoteAudio:()=>({}),incomingStreamHost:null,viewerRole:'operator',bindMediaElementStream(){},syncMediaMuteState(){},syncRemoteVideoStream(){},window:{setTimeout:fn=>fn()}});
const ontrack=shared.slice(shared.indexOf('            peerConnection.ontrack ='),shared.indexOf('            peerConnection.onconnectionstatechange =',shared.indexOf('            peerConnection.ontrack =')));
const setter=shared.slice(shared.indexOf('        setStreamHandlers('),shared.indexOf('        getState()',shared.indexOf('        setStreamHandlers(')));
vm.runInContext(ontrack+'globalThis.runtime={'+setter+'};',context);
context.peerConnection.ontrack({streams:[incoming],track});
assert.equal(bridgeEvents,1);
context.runtime.setStreamHandlers({onLocalStream(){},onRemoteStream:stream=>{void recordingContext.recorder.ensureRemoteAudio(stream);}});
await recordingContext.recorder.ensureRemoteAudio(context.state.remoteStream);
assert.equal(recordings,0,'Muted handoff track waits for availability');
track.muted=false;track.dispatchEvent(new Event('unmute'));
await recorderState.remoteAudioSyncPromise;
assert.equal(recordings,1,'Unmute after handoff starts citizen recording');
track.dispatchEvent(new Event('unmute'));await recorderState.remoteAudioSyncPromise;
assert.equal(recordings,1,'Repeated unmute reuses existing recorder');
assert.equal(bridgeEvents,1,'Track events no longer go to the bridge');
recorderState.shuttingDown=true;track.dispatchEvent(new Event('unmute'));await recorderState.remoteAudioSyncPromise;
assert.equal(recordings,1,'Shutdown must not create a recorder');
assert.match(operator,/callRuntime\.setStreamHandlers\?\.\(\{\s*onLocalStream: attachLocalStreamToWorkbench,\s*onRemoteStream: attachRemoteStreamToWorkbench,/);
console.log('PASS citizen recorder handoff, delayed unmute, reuse, and shutdown');
